### ISSUE TITLE
Image Pull Backoff 

### ISSUE THREAD

**Issue by iamakpatel** [kubecost/cost-analyzer#10]
I have followed https://aws.amazon.com/blogs/containers/how-to-track-costs-in-multi-tenant-amazon-eks-clusters-using-kubecost/ for installing kubecost on eks. 

This is the status of pods:
NAME                                          READY   STATUS             RESTARTS   AGE
kubecost-cost-analyzer-84d85c96d-dpzr5        3/3     Running            0          78m
kubecost-grafana-7d8f9c8dc5-vqgr5             3/3     Running            0          78m
kubecost-kube-state-metrics-f575cb8b4-rvmjc   1/1     Running            0          78m
kubecost-prometheus-node-exporter-tr9jg       0/1     ImagePullBackOff   0          78m
kubecost-prometheus-node-exporter-vfzsm       0/1     ImagePullBackOff   0          78m
kubecost-prometheus-server-df5dbc6f9-2zrts    1/2     ImagePullBackOff   0          78m

I have found the below issues. 

Failed to pull image "prom/node-exporter:v0.18.1": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

Service are failing because it encounters `ImagePullBackOff ` issue.. Would you be able to help ?

**Comment by chipzoller** [comment]
Since this is outdated and not a Kubecost issue directly, closing for organization, but if we need any follow-up we can reopen.
