### ISSUE TITLE
kubecost-prometheus-node-exporter in Pending status.

### ISSUE THREAD

**Issue by neel-zolve** [kubecost/cost-analyzer#11]
**Context** :

the kubecost-prometheus-node-exporter is in pending status and not getting deployed.

**Issue in detail:**

* We installed kubecost using the helm repo as mentioned in the installation steps, but its not getting installed. Attached below the error message.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/101382995/165459811-886ea04f-4775-4aad-be37-b66c1229dda8.png">

* The issue on further checking we found out that, we are already running Prometheus in our default namespace, so its port conflict issue as both  kubecost-prometheus-node exporter and default Prometheus node exporter runs as deamonset and needs same port 9100 and k8s cant allocate it.

* This would be a common issue that could affect anyone running a Prometheus on their own already and trying to install kubecost on top of it.

**Suggestion**:

We saw an alternate option to use in Paid plan  the custom Promethues :- https://guide.kubecost.com/hc/en-us/articles/4407595941015-Custom-Prometheus  but we are not at the moment proceeding with paid plan due to mgmt reasons.

Can we create a custom image for node exporter for Kubecost and change the port say from 9100 to something else and expose it in such case for the free plan, any suggestions.

**Comment by AjayTripathy** [comment]
Hi @neel-zolve the deployed port of node exporter can be modified in our helm chart here: https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/charts/prometheus/templates/node-exporter-daemonset.yaml#L45

If you have additional questions, please file an issue in that repo since it's monitored for issues more.

**Comment by neel-zolve** [comment]
thanks Ajay,
its resolved, we changed the port to say 9200 and it worked

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/101382995/165689975-8da93e3f-b201-49e5-a616-8955eb3dbb05.png">
