### ISSUE TITLE
1 Click Resizing not working in Secondary Cluster

### ISSUE THREAD

**Issue by svelango** [kubecost/cost-analyzer#13]
In federated cluster , 1 click resizing is not working. The UI gives no feedback when button is pressed but API throws error "Application of request sizing is currently only supported for the local Kubecost cluster. Please filter appropriately" which is not bubbled in UI. Ultimately 1 click doesn't work but user doesn't know.

**Comment by jcharcalla** [comment]
This is related to ZD ticket [2227](https://kubecost.zendesk.com/agent/tickets/2227)

I suggest adding the same error message to the UI when trying to '1 click resize' a pod on a secondary cluster from the primary.

**Comment by teevans** [comment]
@biancaburtoiu - Is this something you're working on?

**Comment by biancaburtoiu** [comment]
@teevans I don't have much context on request sizing, I think @michaelmdresser would know more here? Given he's not in at the moment, let me know if you want me to put some time into this.

**Comment by dwbrown2** [comment]
This is a current limitation for 1-click request sizing today. While the basic infrastructure is there to communicate across clusters, this isn't implemented for this feature. 

@Adam-Stack-PM could we add this as a known limitation to our 1-click right-sizing docs unless we think we can address soon?

**Comment by teevans** [comment]
@svelango - Thanks for reporting this! We'll get this fixed in 1.96! I'm going to close this issue and open it in our Frontend repository to track on our end!

@dwbrown2 - Thanks for the context here. We'll get a good error message setup for this.
