### ISSUE TITLE
Migrate Helm chart installation to eks add-on

### ISSUE THREAD

**Issue by devikiran-khode** [kubecost/cost-analyzer#24]
Hello,

Previously I've installed Kubecost using helm chart and want to see if I can migrate this to eks add-on. But I don't see any documents on migration. When I try to install using `aws eks create-addon --addon-name kubecost_kubecost ....`

I'm getting the below error:
`{    "addon": {        "addonName": "kubecost_kubecost",        "clusterName": "my-cluster",        "status": "CREATE_FAILED",        "addonVersion": "v1.99.0-eksbuild.0",        "health": {            "issues": [                {                    "code": "ConfigurationConflict",                    "message": "Conflicts found when trying to apply. Will not continue due to resolve conflicts mode. Conflicts:\nServiceAccount kubecost-cost-analyzer - .metadata.labels.helm.sh/chart\nConfigMap kubecost-cost-analyzer - 
.data.kubecost-token\nConfigMap kubecost-cost-analyzer - .metadata.labels.helm.sh/chart\nConfigMap nginx-conf - .data.n
ginx.conf\nConfigMap nginx-conf - .metadata.labels.helm.sh/chart\nConfigMap external-grafana-config-map - .metadata.lab
els.helm.sh/chart\nPersistentVolumeClaim kubecost-cost-analyzer - .metadata.labels.helm.sh/chart\nClusterRole.rbac.auth
orization.k8s.io kubecost-cost-analyzer - .metadata.labels.helm.sh/chart\nClusterRoleBinding.rbac.authorization.k8s.io
kubecost-cost-analyzer - .metadata.labels.helm.sh/chart\nRole.rbac.authorization.k8s.io kubecost-cost-analyzer - .metad
ata.labels.helm.sh/chart\nRoleBinding.rbac.authorization.k8s.io kubecost-cost-analyzer - .metadata.labels.helm.sh/chart
\nService kubecost-cost-analyzer - .metadata.labels.helm.sh/chart\nDeployment.apps kubecost-prometheus-server - .spec.t
emplate.spec.containers[name=\"prometheus-server\"].image\nDeployment.apps kubecost-cost-analyzer - .metadata.labels.he
lm.sh/chart\nDeployment.apps kubecost-cost-analyzer - .spec.template.spec.containers[name=\"cost-analyzer-frontend\"].i
mage\nDeployment.apps kubecost-cost-analyzer - .spec.template.spec.containers[name=\"cost-model\"].env\nDeployment.apps
kubecost-cost-analyzer - .spec.template.spec.containers[name=\"cost-model\"].env[name=\"HELM_VALUES\"].value"                }            ]        },        "addonArn": "arn:aws:eks:us-east-1:AWS_ACCOUNT:addon/my-cluster/kubecost_kubecost/30c3429
9-3422-4592-478f-128ed1f5b190",        "createdAt": "2023-02-24T14:51:58.888000-06:00",        "modifiedAt": "2023-02-24T14:56:10.048000-06:00",        "tags": {}    }
}`

**Comment by AjayTripathy** [comment]
@linhlam-kc any ideas on this one?

**Comment by linhlam-kc** [comment]
Thank you Ajay.
@devikiran-khode The Amazon EKS add-on deploy Kubecost by generating manifests from the Helm chart then applying them using K8s API instead of using the Helm CLI. By that said, the migration path from Helm chart to EKS add-on is unavailable as of now. If you are using Helm chart and you have custom configuration for your set up, I would recommend to stay with Helm chart to utilize its flexibility and easy to configure. EKS add-on works well if you need a simple Kubecost set up in AWS native way without requiring the custom configuration.

**Comment by devikiran-khode** [comment]
Thank you both. Closing this for now.
