### ISSUE TITLE
Incorrect cost computation for GPU node

### ISSUE THREAD

**Issue by kinihun** [kubecost/cost-analyzer#3]
Hello,
I have a single Azure Standard_NC6 instance in one of my nodepools, it's showing a daily usage cost of over $900. That's more than the monthly cost for that instance.

![image](https://user-images.githubusercontent.com/18234695/96749160-5bd1ee80-13c2-11eb-81c1-0b3d88702419.png)

**Comment by dwbrown2** [comment]
@kinihun can you share what region you are in?

**Comment by kinihun** [comment]
Hi,

My resources are in us-east-2.

Best regards
Olumide

**Comment by AjayTripathy** [comment]
Hi @kinihun , we did have a bug about GPU costs in versions less than 1.67.0. What version are you running? Can you also send a bug report? (available on /settings.html)

**Comment by kinihun** [comment]
I just upgraded to 1.68.0 and the calculation looks fine now.
Thank you.
