### ISSUE TITLE
GitHub site is down / deployment failed

### ISSUE THREAD

**Issue by Sjoerdsjoerd** [kubecost/cost-analyzer#6]
If you go the following link, you will see a 404:
[https://kubecost.github.io/cost-analyzer/](https://kubecost.github.io/cost-analyzer/)

Could you look into this?

![afbeelding](https://user-images.githubusercontent.com/19996084/112231374-e13e2100-8c36-11eb-9ea7-0a9610ab5d4d.png)

**Comment by AjayTripathy** [comment]
Hi @Sjoerdsjoerd this is mainly a repository for our helm tarballs. https://kubecost.github.io/cost-analyzer/index.yaml seems up to me. Can you share the helm command you used to install? I just ran one and it seems to work:

```
atripathy@Ajays-MacBook-Pro cost-model % helm repo add kubecost https://kubecost.github.io/cost-analyzer/                                                               

"kubecost" has been added to your repositories
atripathy@Ajays-MacBook-Pro cost-model % helm upgrade kubecost kubecost/cost-analyzer --namespace kubecost --set kubecostToken="NHRyaXBhdGh5QGdtYWlsLmNvbQ==xm343yadf98"
```

**Comment by Sjoerdsjoerd** [comment]
Hey @AjayTripathy,

It seems to be working fine now.
Maybe downtime, idk?

Thanks for looking into it 👍
