### ISSUE TITLE
add ability to change sender name and icon when sending to slack webhooks

### ISSUE THREAD

**Issue by kplimack** [kubecost/cost-analyzer#95]
When sending to slack webhooks, it would be great if we could customize both the Name and Icon of the sender, otherwise its pretty ugly

**Comment by chipzoller** [comment]
Hi @kplimack, would you mind either filing a feature request [here](https://github.com/kubecost/cost-analyzer-helm-chart/issues/new/choose) or come talk to us using [other ways](https://docs.kubecost.com/#staying-in-the-loop)?
