### ISSUE TITLE
Cannot find persistance volume pricing for asia-southeast2

### ISSUE THREAD

**Issue by robertarifin-pinhome** [kubecost/cost-analyzer#96]
Hello everyone, when I try to see the logs for the kubecost model helm chart, I encountered this error:
 ```Persistent Volume pricing not found for standard-rwo: asia-southeast2,pd-balanced```
 
 Is it not possible to get the pv price for my region?

**Comment by chipzoller** [comment]
Hi @robertarifin-pinhome, would you mind either following the link on the Helm chart code repo to [open a support ticket](https://github.com/kubecost/cost-analyzer-helm-chart/issues/new/choose) or come talk to us using [other ways](https://docs.kubecost.com/#staying-in-the-loop)?
